# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Lingua-Stem
version:      0.80
version_from: lib/Lingua/Stem.pm
installdirs:  site
requires:
    Lingua::GL::Stemmer:           0
    Lingua::PT::Stemmer:           0
    Lingua::Stem::Fr:              0.02
    Lingua::Stem::It:              0
    Lingua::Stem::Ru:              0
    Lingua::Stem::Snowball::Da:    1.01
    Lingua::Stem::Snowball::No:    1.00
    Lingua::Stem::Snowball::Se:    1.01
    Text::German:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
